CREATE TABLE users (id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT, username TEXT NOT NULL, passwd TEXT NOT NULL, name TEXT NOT NULL, phone TEXT NOT NULL, avator TEXT NOT NULL); 

CREATE TABLE meetups (id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT, name TEXT NOT NULL, avatar TEXT NOT NULL, content TEXT NOT NULL, category TEXT NOT NULL, address TEXT NOT NULL, latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL, status BIGINT NOT NULL, start_time TEXT NOT NULL, end_time TEXT NOT NULL);
